// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_posts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPosts = `-- name: GetPosts :many
SELECT 
    posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id, 
    ff.user_id 
FROM posts 
JOIN feed_follows AS ff ON posts.feed_id = ff.feed_id 
WHERE ff.user_id = $1
ORDER BY published_at DESC
`

type GetPostsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetPosts(ctx context.Context, userID uuid.UUID) ([]GetPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByLimit = `-- name: GetPostsByLimit :many
SELECT 
    posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id, 
    ff.user_id 
FROM posts 
JOIN feed_follows AS ff ON posts.feed_id = ff.feed_id 
WHERE ff.user_id = $1
ORDER BY published_at DESC
LIMIT $2
`

type GetPostsByLimitParams struct {
	UserID uuid.UUID
	Limit  int32
}

type GetPostsByLimitRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description string
	PublishedAt time.Time
	FeedID      uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetPostsByLimit(ctx context.Context, arg GetPostsByLimitParams) ([]GetPostsByLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByLimit, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByLimitRow
	for rows.Next() {
		var i GetPostsByLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
